/**
 * Generate a deployer account for Cyprus-1 and write it into .env.
 *
 * A Quai address encodes its shard in its first 9 bits, so not every keypair lands in
 * Cyprus-1 — a random key has roughly a 1-in-512 chance. `QuaiHDWallet` walks derivation
 * indices until one does, which is the same BIP-44 mechanism the FundX backend will use to
 * give every user an address from a single mnemonic.
 *
 *   node scripts/newAccount.js
 *
 * The key is written to .env (gitignored) and never printed, so it cannot end up in a
 * terminal scrollback or a pasted log. Testnet only.
 */

const fs = require("node:fs")
const path = require("node:path")
const quais = require("quais")

const ENV = path.join(__dirname, "..", ".env")

async function main() {
  const mnemonic = quais.Mnemonic.fromEntropy(quais.randomBytes(32))
  const wallet = quais.QuaiHDWallet.fromMnemonic(mnemonic)

  // Account 0, first derived address that lands in Cyprus-1.
  const info = await wallet.getNextAddress(0, quais.Zone.Cyprus1)
  const privateKey = wallet.getPrivateKey(info.address)

  if (!info.address.toLowerCase().startsWith("0x00")) {
    throw new Error(`Derived address is not in Cyprus-1: ${info.address}`)
  }

  const existing = fs.existsSync(ENV) ? fs.readFileSync(ENV, "utf8") : ""
  if (/^CYPRUS1_PK=.+/m.test(existing)) {
    console.log("\n  .env already has CYPRUS1_PK — refusing to overwrite it.")
    console.log("  Remove that line first if you really want a new account.\n")
    process.exit(1)
  }

  const block = [
    "# Generated by scripts/newAccount.js — testnet only, never commit.",
    `DEPLOYER_MNEMONIC="${mnemonic.phrase}"`,
    `CYPRUS1_PK="${privateKey}"`,
    `DEPLOYER_ADDRESS="${info.address}"`,
    "",
  ].join("\n")

  fs.writeFileSync(ENV, existing ? `${existing.trimEnd()}\n\n${block}` : block, { mode: 0o600 })

  console.log("")
  console.log("  address   ", info.address)
  console.log("  derivation", `account 0, index ${info.index}`)
  console.log("  written to", ENV, "(mode 600, gitignored)")
  console.log("")
  console.log("  Next: fund it at https://orchard.faucet.quai.network")
  console.log("")
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
