services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: xpay
      POSTGRES_PASSWORD: xpay
      POSTGRES_DB: xpay
    ports:
      - "5433:5432"
    volumes:
      - xpay_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U xpay"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  xpay_postgres_data:
